betty/betty/urls.py
from courses import views
from django.conf.urls import url, include
from django.contrib import admin
from users.views import BettyCompanyRegistrationView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', BettyCompanyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^courses/', include('courses.urls')),
    url(r'^reports/', include('reports.urls')),
    url(r'^$', views.HomeView.as_view(), name="index"),
]

betty/courses/urls.py
from courses.views import CourseCreationView, CoursesListView
from django.conf.urls import url

from . import views

urlpatterns = [
    # Courses
    url(r'^create/$', views.CourseCreationView.as_view(), name='course_create'),
    url(r'^edit/(?P<pk>[0-9]+)/$', views.CourseUpdateView.as_view(), name='course_update'),
    url(r'^list/$', views.CoursesListView.as_view(), name='course_list'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.CourseDetailView.as_view(), name='course_detail'),
    url(r'^delete/(?P<pk>[0-9]+)/$', views.CourseDeleteView.as_view(), name='course_delete'),

    #Period
    url(r'^period/edit/(?P<pk>[0-9]+)/$', views.CoursePeriodUpdateView.as_view(), name='period_update'),
    url(r'^period/delete/(?P<pk>[0-9]+)/$', views.CoursePeriodDeleteView.as_view(), name='period_delete'),
    url(r'^detail/(?P<course_id>[0-9]+)/period/create/$', views.CoursePeriodCreationView.as_view(), name='period_create'),

    url(r'^student/create/$', views.StudentCreationView.as_view(), name='student_create'),
    url(r'^student/multiple/(?P<amount>[0-9]+)/$', views.manage_students, name='multiple_student_create'),
    url(r'^student/edit/(?P<pk>[0-9]+)/$', views.StudentUpdateView.as_view(), name='student_update'),
    url(r'^student/list/$', views.StudentsListView.as_view(), name='student_list'),
    url(r'^student/detail/(?P<pk>[0-9]+)/$', views.StudentDetailView.as_view(), name='student_detail'),
    url(r'^student/delete/(?P<pk>[0-9]+)/$', views.StudentDeleteView.as_view(), name='student_delete'),

    url(r'^teacher/create/$', views.TeacherCreationView.as_view(), name='teacher_create'),
    url(r'^teacher/edit/(?P<pk>[0-9]+)/$', views.TeacherUpdateView.as_view(), name='teacher_update'),
    url(r'^teacher/list/$', views.TeachersListView.as_view(), name='teacher_list'),
    url(r'^teacher/detail/(?P<pk>[0-9]+)/$', views.TeacherDetailView.as_view(), name='teacher_detail'),
    url(r'^teacher/delete/(?P<pk>[0-9]+)/$', views.TeacherDeleteView.as_view(), name='teacher_delete'),

    url(r'^client/create/$', views.ClientCompanyCreationView.as_view(), name='client_create'),
    url(r'^client/edit/(?P<pk>[0-9]+)/$', views.ClientCompanyUpdateView.as_view(), name='client_update'),
    url(r'^client/list/$', views.ClientCompanyListView.as_view(), name='client_list'),
    url(r'^client/detail/(?P<pk>[0-9]+)/$', views.ClientCompanyDetailView.as_view(), name='client_detail'),
    url(r'^client/delete/(?P<pk>[0-9]+)/$', views.ClientCompanyDeleteView.as_view(), name='client_delete'),

    url(r'^detail/(?P<course_id>[0-9]+)/activity/create/$', views.ActivityCreationView.as_view(), name='activity_create'),
    url(r'^detail/(?P<course_id>[0-9]+)/activity/edit/(?P<pk>[0-9]+)/$', views.ActivityUpdateView.as_view(), name='activity_update'),
    url(r'^activity/list/$', views.ActivityListView.as_view(), name='activity_list'),
    url(r'^activity/detail/(?P<pk>[0-9]+)/$', views.ActivityDetailView.as_view(), name='activity_detail'),
    url(r'^activity/delete/(?P<pk>[0-9]+)/$', views.ActivityDeleteView.as_view(), name='activity_delete'),

    url(r'^detail/(?P<course_id>[0-9]+)/end/$', views.end_course, name='end_course'),
    url(r'^detail/(?P<course_id>[0-9]+)/start/$', views.start_course, name='start_course'),
    url(r'^detail/(?P<course_id>[0-9]+)/end_period/(?P<period_id>[0-9]+)$', views.end_period, name='end_period'),
    url(r'^raise_error/$', views.raise_error, name='raise_error'),
    url(r'^raise_error_delay/$', views.raise_error_delay, name='raise_error_delay'),

]

betty/courses/models.py
from __future__ import unicode_literals

import logging
from datetime import datetime, date

from dateutil.relativedelta import relativedelta
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from users.models import Company, UserManager, UserRole

# Get an instance of a logger
logger = logging.getLogger(__name__)

class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name.decode("utf-8")


class ClientCompany(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200, null=True)
    contact_name = models.CharField(max_length=100, null=True)
    contact_email = models.EmailField(null=True)
    company = models.ForeignKey(Company)
    notifications_active = models.BooleanField(default=True)
    sales_associates = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name.decode("utf-8")

    def __unicode__(self):
        return self.name


class StudentManager(models.Manager):

    def create_student(self, cleaned_data, company_id):
        new_student = Student.objects.create(
            name=cleaned_data['name'],
            email=cleaned_data['email'],
            phone=cleaned_data['phone'],
            client=cleaned_data['client'],
            company=Company.objects.get(pk=company_id)
        )
        new_student.sales_associates = cleaned_data['sales_associates']
        new_student.save()
        return new_student

    def get_activities(self, company, student, course, period=None, include_comments=True):
        queryset = Activity.objects.filter(company=company, student=student, course=course).order_by('type', 'name')
        if period is not None:
            queryset = queryset.filter(period=period)
        if not include_comments:
            queryset = queryset.filter(~Q(type='feedback') & ~Q(type='period_feedback'))
        return queryset


class Student(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    client = models.ForeignKey(ClientCompany, null=True, blank=True)
    company = models.ForeignKey(Company)
    sales_associates = models.ManyToManyField(User, blank=True)

    objects = StudentManager()

    def __str__(self):
        return "%s - %s" % (self.client.name, self.name)

    def __unicode__(self):
        return "%s - %s" % (self.client.name, self.name)


class TeacherManager(models.Manager):

    def create_teacher(self, cleaned_data, company_id):
        
        new_user = User.objects.create(
            first_name = cleaned_data['first_name'],
            last_name = cleaned_data['last_name'],
            username=cleaned_data['username'],
            email=cleaned_data['email'],
        )
        new_user.set_password('changeme')

        new_user.save()

        user_manager = UserManager()
        new_profile = user_manager.create_profile(new_user, Company.objects.get(pk=company_id), [UserRole.objects.get(name='teacher')])

        new_teacher = Teacher.objects.create(
            name=cleaned_data['first_name'] + ' ' + cleaned_data['last_name'],
            email=cleaned_data['email'],
            phone=cleaned_data['phone'],
            country=cleaned_data['country'],
            specialty=cleaned_data['specialty'],
            company=Company.objects.get(pk=company_id),
            user=new_user
        )

        return new_teacher


class Teacher(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(null=True)
    phone = models.CharField(max_length=50, null=True)
    company = models.ForeignKey(Company)
    user = models.OneToOneField(User)
    country = models.CharField(max_length=50, null=True)
    specialty = models.TextField(null=True)

    objects = TeacherManager()

    def __str__(self):
        return self.name.decode("utf-8")

    def __unicode__(self):
        return self.name


class Course(models.Model):

    # Code (CLIENT_COMPANY-SEQUENCE)
    code = models.CharField(max_length=100)
    # Level
    level = models.ForeignKey(Level, null=True, blank=True)
    # Company
    company = models.ForeignKey(Company)
    # Client Company
    client = models.ForeignKey(ClientCompany, null=True, blank=True)
    # Address
    address = models.CharField(max_length=200)
    # Schedule
    # @todo:gustavo the way to store a course schedule should probably follow rrule standards
    schedule = models.CharField(max_length=200)
    # Start Date
    start_date = models.DateField()
    # End Date
    end_date = models.DateField()
    # List of Students
    students = models.ManyToManyField(Student, blank=True)

    teacher = models.ForeignKey(Teacher, null=True, on_delete=models.SET_NULL)

    is_active = models.BooleanField(default=True)

    duration = models.IntegerField(default=48)

    def is_over(self):
        now = datetime.now()
        if self.end_date + relativedelta(days=3) <= date(now.year, now.month, now.day):
            return True
        return False

    def __str__(self):
        return self.code.decode("utf-8")

    def __unicode__(self):
        return "%s - %s" % (self.code, self.level)


class CoursePeriod(models.Model):

    course = models.ForeignKey(Course)
    start_date = models.DateField()
    end_date = models.DateField()
    is_active = models.BooleanField()

    def is_in_buffer(self):
        """
        This returns whether the period is in it's final days or buffer.
        :return: (boolean) is in buffer.
        """
        now = datetime.now()
        if self.get_buffer_start_date() <= date(now.year, now.month, now.day):
            return True
        return False

    def get_buffer_start_date(self):
        return self.end_date + relativedelta(days=-5)

    def __str__(self):
        return "%s to %s" % (self.start_date.strftime('%b %d, %Y'), self.end_date.strftime('%b %d, %Y'))


class ActivityManager(models.Manager):

    def create_activities(self, company, course, student):
        """
        This function creates activities for a given student in a course. It will find the company's activities set for
        their courses from CompanyActivity if they have been set. Otherwise, it will create a default set of activities.

        :param company:
        :param course:
        :param student:
        :return:
        """
        try:
            activities = list(CompanyActivity.objects.filter(company=company).values('name', 'type'))
            if len(activities) == 0:
                raise Exception('No activities found for company %s.' % company)
        except:
            activities = [
                {
                    'name': 'Comments',
                    'type': 'feedback'
                },
                {
                    'name': 'Test 1',
                    'type': 'test'
                },
                {
                    'name': 'Test 2',
                    'type': 'test'
                },
                {
                    'name': 'Test 3',
                    'type': 'test'
                },
            ]

        for activity in activities:
            # Create activities for each of the periods in the course
            if activity['type'] in ['skill', 'period_feedback']:
                for period in course.courseperiod_set.filter(is_active=True).order_by('start_date'):
                    Activity.objects.create(
                        company=company,
                        course=course,
                        student=student,
                        name=activity['name'],
                        type=activity['type'],
                        period=period
                    )
                continue
            # Create activities for the whole course (Final test and Portfolio)
            Activity.objects.create(
                company=company,
                course=course,
                student=student,
                name=activity['name'],
                type=activity['type'],
            )


class Activity(models.Model):
    """
    The different activities available for students enroled in a course.
    They can be 'test', 'skill', 'total', 'pass/fail'
    """

    name = models.CharField(max_length=100, blank=True)
    score = models.FloatField(null=True, blank=True)
    comment = models.TextField(null=True, blank=True)
    type = models.CharField(max_length=100, default='task')

    # Each activity is associated to one course
    course = models.ForeignKey(Course)
    # Each activity is associated to one student
    student = models.ForeignKey(Student)
    company = models.ForeignKey(Company)

    period = models.ForeignKey(CoursePeriod, null=True, blank=True)

    objects = ActivityManager()

    def __str__(self):
        return self.name.decode("utf-8")

    def __unicode__(self):
        return self.name


class CompanyActivity(models.Model):
    """
    Default set of activities for courses created in a given company
    """
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.name.decode("utf-8")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "company activities"


class CompanySettings(models.Model):
    name = models.CharField(max_length=100)
    value = models.CharField(max_length=100)
    company = models.ForeignKey(Company)

    def __str__(self):
        return self.name.decode("utf-8")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "company settings"

betty/courses/templates/activity_detail.html
{% extends "base.html" %}
{% load filters %}
{% load i18n %}

{% block content %}
<h1>Activity Detail</h1>
<h1>Activity Name: {{ activity.name }}</h1>
<p>Type: {{ activity.type }}</p>
<p>Score: {{ activity.score }}</p>
<p>Student: {{ activity.student.name }}</p>
<p>Course: {{ activity.course.code }}</p>

<a href="{% url 'activity_update' 1 activity.id %}">Edit Activity</a>
<a href="{% url 'activity_delete' activity.id %}">Delete Activity</a>
{% endblock %}

betty/courses/templates/activity_list.html
{% extends "base.html" %}
{% load filters %}
{% load i18n %}

{% block content %}
<h1>Activities</h1>
{#{% if user|has_role:'manager' or user|has_role:'admin' %}#}
{#    <a href="{% url 'activity_create' %}">{% trans "Create Activity" %}</a>#}
{#{% endif %}#}
<ul>
{% for activity in object_list %}
    <li><a href="{% url 'activity_detail' activity.id %}">{{ activity.name }} - {{ activity.type }} - {{ activity.course.code }} - {{ activity.student.name }}</a></li>
{% empty %}
    <li>No Activities yet.</li>
{% endfor %}
</ul>
{% endblock %}

betty/courses/templates/activity_update.html
{% extends "base.html" %}
{% load i18n %}
{% load filters %}

{% block content %}
    <h1>Activity Edit</h1>
    <a href="{% url 'course_detail' form.course %}">{% trans "Back to Course" %}</a>
    <form method="post" action=".">
        {% csrf_token %}
        {% if object.type == 'feedback' or object.type == 'period_feedback' %}
            {{ form.comment.errors }}
            {{ form.comment.label_tag }}
            {{ form.comment }}
        {% else %}
            {{ form.score.errors }}
            {{ form.score.label_tag }}
            {{ form.score }}
        {% endif %}
        <input type="submit" value="{% trans 'Update' %}" />
    </form>
{% endblock %}

betty/courses/templates/client_detail.html
{% extends "base.html" %}
{% load filters %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <h1 class="text-center" id="title">Client Details - {{ client.name }}</h1>
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <td>Name</td>
                    <td id="name">{{ client.name }}</td>
                </tr>
                <tr>
                    <td>Address</td>
                    <td id="address">{{ client.address }}</td>
                </tr>
                <tr>
                    <td>Client Contact</td>
                    <td id="contact_name">{{ client.contact_name }}</td>
                </tr>
                <tr>
                    <td>Client Email</td>
                    <td id="email">{{ client.contact_email }}</td>
                </tr>
                <tr>
                    <td>Notifications Active</td>
                    <td id="name">{{ client.notifications_active }}</td>
                </tr>
                <tr>
                    <td>Sales Associates</td>
                    <td id="name">
                        {% for associate in client.sales_associates.all %}
                            {% if associate.first_name %}
                                {{ associate.first_name }} {{ associate.last_name }}
                            {% else %}
                                {{ associate }}
                            {% endif %}
                            {% if forloop.counter < client.sales_associates.count %},
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            </table>
        </div>
        <div class="center-block btn-group-vertical">
            <a class="btn btn-default" href="{% url 'client_list' %}">Back to Client List</a>
            <a id="edit_btn" class="btn btn-default" href="{% url 'client_update' client.id %}">Edit Client</a>
            <a id="delete_btn" class="btn btn-danger" href="{% url 'client_delete' client.id %}">Delete Client</a>
        </div>
    </div>
{% endblock %}

betty/courses/templates/client_list.html
{% extends "base.html" %}
{% load filters %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <h1 class="text-center">Clients</h1>
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <th>{% trans 'Client Name' %}</th>
                    <th>{% trans 'Contact Name' %}</th>
                    <th>{% trans 'Contact Email' %}</th>
                    <th>{% trans 'Notifications' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
                {% for client in object_list %}
                    <tr>
                        <td id="name">{{ client.name }}</td>
                        <td id="contact_name">{{ client.contact_name }}</td>
                        <td id="contact_email">{{ client.contact_email }}</td>
                        <td id="contact_notifications">{{ client.notifications_active }}</td>
                        <td><a id="details_btn" class="btn btn-default" href="{% url 'client_detail' client.id %}">View Details</a></td>
                    </tr>

                {% empty %}
                    <tr><td>No Clients yet.</td></tr>
                {% endfor %}
            </table>
        </div>
        {% if user|has_role:'manager' or user|has_role:'admin' %}
            <div class="center-block btn-group-vertical">
                <a id="create_btn" class="btn btn-success" href="{% url 'client_create' %}">{% trans "Create Client" %}</a>
            </div>
        {% endif %}
    </div>

{% endblock %}

betty/courses/templates/client_update.html
{% extends "base.html" %}
{% load i18n %}
{% load filters %}

{% block content %}
    <h1 class="text-center">Client Edit</h1>
    <form method="post" action=".">
    {% csrf_token %}
    <form role=”form“ method="post" action=".">
        {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}">Client Company Name</label>
            {{ form.name|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.address.errors }}
            <label for="{{ form.address.id_for_label }}">Address:</label>
            {{ form.address|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.contact_name.errors }}
            <label for="{{ form.contact_name.id_for_label }}">Contact Name (HR):</label>
            {{ form.contact_name|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.contact_email.errors }}
            <label for="{{ form.contact_email.id_for_label }}">Contact Email (HR Reports)</label>
            {{ form.contact_email|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.notifications_active.errors }}
            <label for="{{ form.notifications_active.id_for_label }}">Send Notifications?</label>
            {{ form.notifications_active|add_css:"form-control" }}
        </div>

        <div class="form-group">
            {{ form.sales_associates.errors }}
            <label for="{{ form.sales_associates.id_for_label }}">Sales Associates</label>
            {{ form.sales_associates|add_css:"form-control multiselect_field" }}
        </div>

        <div class="center-block btn-group-vertical">
            <input id="update_btn" class="btn btn-success" type="submit" value="{% trans 'Update' %}" />
            <a class="btn btn-default" href="{% url 'client_detail' client.id %}">{% trans "Cancel" %}</a>
        </div>

    </form>

{% endblock %}

betty/courses/templates/course_create.html
{% extends "base.html" %}
{% load i18n %}
{% load filters %}

{% block content %}

    <form class="container-fluid" method="post" action=".">
        <h1 class="text-center">Create a Course</h1>
        {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.level.errors }}
            <label for="{{ form.level.id_for_label }}">Course Level</label>
            {{ form.level|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.client.errors }}
            <label for="{{ form.client.id_for_label }}">Course Client</label>
            <select id="{{ form.client.auto_id }}" name="{{ form.client.name }}" class="form-control" onchange="changed">
                {% for x,y in form.fields.client.choices %}
                    <option value="{{ x }}"{% if form.fields.client.choices == x %} selected{% endif %}>{{ y }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            {{ form.address.errors }}
            <label for="{{ form.address.id_for_label }}">Course Address (Where the class will take place)</label>
            {{ form.address|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.schedule.errors }}
            <label for="{{ form.schedule.id_for_label }}">Course Schedule (e.g. Every Thursday at 5pm)</label>
            {{ form.schedule|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.start_date.errors }}
            <label for="{{ form.start_date.id_for_label }}">Course Start Date</label>
            {{ form.start_date|add_css:"form-control datepicker" }}
        </div>
        <div class="form-group">
            {{ form.end_date.errors }}
            <label for="{{ form.end_date.id_for_label }}">Course End Date</label>
            {{ form.end_date|add_css:"form-control datepicker" }}
        </div>
        <h5 class="text-center">
            Filter your students by client or name by clicking the box below and typing in the search box!
        </h5>
        <div class="form-group">
            {{ form.students.errors }}
            <label for="{{ form.students.id_for_label }}">Enrolled Students</label>
            {{ form.students|add_css:"form-control multiselect_field" }}
        </div>
        <div class="form-group">
            {{ form.teacher.errors }}
            <label for="{{ form.teacher.id_for_label }}">Course Teacher</label>
            {{ form.teacher|add_css:"form-control" }}
        </div>
        <div class="form-group">
            {{ form.duration.errors }}
            <label for="{{ form.duration.id_for_label }}">Course Duration</label>
            {{ form.duration|add_css:"form-control" }}
        </div>
        <div class="center-block btn-group-vertical">
            <input id="create_btn" class="btn btn-success create_btn" type="submit" value="{% trans 'Create Course' %}" />
        </div>

    </form>
{% endblock %}

betty/courses/templates/period_create.html
{% extends "base.html" %}
{% load i18n %}
{% load filters %}

{% block content %}
    <form class="container-fluid" method="post" action=".">
        {% csrf_token %}

        <h1 class="text-center">Create a Period for Course {{ course.code }}</h1>
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.start_date.errors }}
            <label for="{{ form.start_date.id_for_label }}">Start date:</label>
            {{ form.start_date|add_css:"form-control datepicker" }}
        </div>
        <div class="form-group">
            {{ form.end_date.errors }}
            <label for="{{ form.end_date.id_for_label }}">End date:</label>
            {{ form.end_date|add_css:"form-control datepicker" }}
        </div>
        <div class="center-block btn-group-vertical">
            <input id="update_btn" class="btn btn-success create_btn" type="submit" value="{% trans 'Create Period' %}" />
            <a class="btn btn-default" href="{% url 'course_detail' course.id %}">{% trans "Back to Course Details" %}</a>
        </div>

    </form>
{% endblock %}

betty/courses/templates/student_detail.html
{% extends "base.html" %}
{% load filters %}
{% load i18n %}

{% block content %}
    <div class="container-fluid">
        <h1 class="text-center">Student Details - {{ student.name }}</h1>
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <td>Client</td>
                    <td id="client_name">{{ student.client.name }}</td>
                </tr>
                <tr>
                    <td>Name</td>
                    <td id="name">{{ student.name }}</td>
                </tr>
                <tr>
                    <td>Phone</td>
                    <td id="phone">{{ student.phone }}</td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td id="email">{{ student.email }}</td>
                </tr>
                <tr>
                    <td>Sales Associates</td>
                    <td id="name">
                        {% for associate in student.sales_associates.all %}
                            {% if associate.first_name %}
                                {{ associate.first_name }} {{ associate.last_name }}
                            {% else %}
                                {{ associate }}
                            {% endif %}
                            {% if forloop.counter < client.sales_associates.count %},
                            {% endif %}
                        {% endfor %}
                    </td>
                </tr>
            </table>
        </div>

        <h1>{% trans 'Courses' %}</h1>
        <div class="table-responsive">
            <table class="table table-bordered">
                <tr>
                    <th>{% trans 'Course Code' %}</th>
                    <th>{% trans 'Course Level' %}</th>
                    {% if user|has_role:'manager' or user|has_role:'admin' %}
                        <th>{% trans 'Actions' %}</th>
                    {% endif %}

                </tr>
                {% for course in student.course_set.all %}
                    <tr>
                        <td>
                            {{ course.code }}
                        </td>
                        <td>
                            {{ course.level }}
                        </td>
                        {% if user|has_role:'manager' or user|has_role:'admin' %}
                            <td>
                                <a class="btn btn-default" href="{% url 'course_detail' course.id %}">View Course</a>
                            </td>
                        {% endif %}
                    </tr>
                {% empty %}
                    <li>No Courses yet.</li>
                {% endfor %}
            </table>
        </div>
        {% if user|has_role:'manager' or user|has_role:'admin' %}
            <div class="center-block btn-group-vertical">
                <a class="btn btn-default" href="{% url 'student_list' %}">Back to Student List</a>
                <a id="edit_btn" class="btn btn-default" href="{% url 'student_update' student.id %}">Edit Student</a>
                <a id="delete_btn" class="btn btn-danger" href="{% url 'student_delete' student.id %}">Delete Student</a>
            </div>
        {% endif %}
    </div>
{% endblock %}

betty/courses/templates/teacher_detail.html
{% extends "base.html" %}
{% load filters %}
{% load i18n %}

{% block content %}

    <h1 class="text-center">Teacher Detail</h1>
    <div class="table-responsive">
        <table class="table">
            <tr>
                <td>Name</td>
                <td id="name">{{ teacher.name }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td class="teacher_email">{{ teacher.email }}</td>
            </tr>
            <tr>
                <td>Phone</td>
                <td id="phone">{{ teacher.phone }}</td>
            </tr>
            <tr>
                <td>Country of Origin</td>
                <td id="country">{{ teacher.country }}</td>
            </tr>
            <tr>
                <td>Specialty</td>
                <td id="specialty">{{ teacher.specialty }}</td>
            </tr>
        </table>
    </div>

    <h1>{% trans 'Courses Assigned' %}</h1>
    <div class="table-responsive">
        <table class="table table-bordered">
            <tr>
                <th>{% trans 'Course Code' %}</th>
                <th>{% trans 'Course Level' %}</th>
                <th>{% trans 'Actions' %}</th>
            </tr>
            {% for course in teacher.course_set.all %}
                <tr>
                    <td>
                        {{ course.code }}
                    </td>
                    <td>
                        {{ course.level }}
                    </td>
                    <td>
                        <a class="btn btn-default" href="{% url 'course_detail' course.id %}">View Course</a>
                    </td>
                </tr>
            {% empty %}
                <li>No Courses yet.</li>
            {% endfor %}
        </table>
    </div>
    <div class="center-block btn-group-vertical">
        <a class="btn btn-default" href="{% url 'teacher_list' %}">Back to Teacher List</a>
        <a id="edit_btn" class="btn btn-default" href="{% url 'teacher_update' teacher.id %}">{% trans 'Edit Teacher' %}</a>
        <a id="delete_btn" class="btn btn-danger" href="{% url 'teacher_delete' teacher.id %}">{% trans 'Delete Teacher' %}</a>
    </div>

{% endblock %}